version: '3'
services:
  mongodb-services:
    image: mongo
    container_name: mongodb-services
    restart: always
    env_file:
      - ./app.env

    ports:
      - '27017:27017'
    volumes:
      - mongodb-services:/data/db
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  mongodb-services:
  redisDB: